export const GET_CURRENT_USER_START:string = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS:string = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE:string = 'GET_CURRENT_USER_FAILURE';

export const REMOVE_CURRENT_USER: string = 'REMOVE_CURRENT_USER';
export const UPDATE_CURRENT_USER: string = 'UPDATE_CURRENT_USER';